- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: 
          - "Hello World! from master branch............."
          #- avengers_branch - "{{ avengers_branch }}"
          #- source_control_branch - "{{ source_control_branch }}"
          
    - name: Show env variable
      debug:
        msg: "{{ lookup('env','PWD') }}"
        
    - name: shell
      shell: "ls -ltr {{ lookup('env','PWD') }}"
      register: shell
     
    - name: debug shell
      debug: 
        msg: "{{ shell }}"
