- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: 
          - "Hello World! from development branch"
          #- avengers_branch - "{{ avengers_branch }}"
          #- source_control_branch - "{{ source_control_branch }}"
